apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "golem-k8s.fullname" . }}
  labels:
    app: {{ template "golem-k8s.name" . }}
    chart: {{ template "golem-k8s.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  globals.json: |-
    {
      "node_name": "{{ template "golem-k8s.fullname" . }}",
      "subnet": "{{ .Values.golemsp.globals.subnet }}",
      "account": "{{ .Values.golemsp.globals.account }}"
    }
  hardware.json: |-
    {
      "active": "default",
      "profiles": {
        "default": {
          "cpu_threads": {{ .Values.golemsp.hardware.cpu_threads }},
          "mem_gib": {{ .Values.golemsp.hardware.mem_gib }},
          "storage_gib": {{ .Values.golemsp.hardware.storage_gib }}
        }
      }
    }
  presets.json: |-
    {
      "active": [
        "wasmtime",
        "vm"
      ],
      "presets": [
        {
          "name": "default",
          "exeunit-name": "wasmtime",
          "pricing-model": "linear",
          "usage-coeffs": {
            "cpu": 1.0,
            "duration": 0.1,
            "initial": 1.0
          }
        },
        {
          "name": "vm",
          "exeunit-name": "vm",
          "pricing-model": "linear",
          "usage-coeffs": {
            "duration": 4.722222222222223e-6,
            "cpu": 0.00002361111111111111,
            "initial": 0.0
          }
        },
        {
          "name": "wasmtime",
          "exeunit-name": "wasmtime",
          "pricing-model": "linear",
          "usage-coeffs": {
            "initial": 0.0,
            "duration": 4.722222222222223e-6,
            "cpu": 0.00002361111111111111
          }
        }
      ]
    }