apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "golem-k8s.fullname" . }}
  labels:
    {{- include "golem-k8s.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "golem-k8s.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "golem-k8s.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "golem-k8s.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: dev-kvm
              mountPath: /dev/kvm
            - name: globals-json
              mountPath: /root/.local/share/ya-provider/globals.json
              subPath: globals.json
            - name: hardware-json
              mountPath: /root/.local/share/ya-provider/hardware.json
              subPath: hardware.json
            - name: presets-json
              mountPath: /root/.local/share/ya-provider/presets.json
              subPath: presets.json
            {{- if .Values.additionalVolumeMounts }}
            {{- toYaml .Values.additionalVolumeMounts | nindent 12 }}
            {{- end }}
      volumes:
        - name: dev-kvm
          hostPath:
            path: /dev/kvm
        - name: globals-json
          configMap:
            name: {{ template "golem-k8s.fullname" . }}
            items:
              - key: globals.json
                path: globals.json
        - name: hardware-json
          configMap:
            name: {{ template "golem-k8s.fullname" . }}
            items:
              - key: hardware.json
                path: hardware.json
        - name: presets-json
          configMap:
            name: {{ template "golem-k8s.fullname" . }}
            items:
              - key: presets.json
                path: presets.json
        {{- if .Values.additionalVolumes }}
        {{- toYaml .Values.additionalVolumes | nindent 10 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
